<?php

return [

    /*
    |--------------------------------------------------------------------------
    | نگاشت معنایی آیکون‌ها
    |--------------------------------------------------------------------------
    |
    | کامپوننت‌ها هرگز نام مستقیم آیکون را در Blade نمی‌نویسند، فقط از طریق
    | theme_icon('کلید') به آن دسترسی دارند. جایگزینی ست آیکون = فقط این فایل.
    |
    */

    'icons' => [
        // ناوبری
        'dashboard' => 'o-squares-2x2',
        'company' => 'o-building-office',
        'user' => 'o-user',
        'users' => 'o-user-group',
        'settings' => 'o-cog-6-tooth',
        'logout' => 'o-arrow-left-on-rectangle',
        'menu' => 'o-bars-3',

        // ماژول‌ها
        'order' => 'o-shopping-cart',
        'product' => 'o-cube',
        'inventory' => 'o-building-storefront',
        'shipping' => 'o-truck',
        'expense' => 'o-banknotes',
        'invoice' => 'o-document-text',
        'project' => 'o-briefcase',
        'timesheet' => 'o-clock',
        'crm' => 'o-heart',
        'report' => 'o-chart-bar',

        // عملیات
        'add' => 'o-plus',
        'edit' => 'o-pencil',
        'delete' => 'o-trash',
        'search' => 'o-magnifying-glass',
        'filter' => 'o-funnel',
        'save' => 'o-check',
        'clear' => 'o-x-mark',
        'login' => 'o-arrow-left-end-on-rectangle',
        'email' => 'o-envelope',
        'password' => 'o-lock-closed',
        'activate' => 'o-check-circle',
        'deactivate' => 'o-no-symbol',
        'assign-role' => 'o-identification',
        'invite' => 'o-paper-airplane',
        'employee' => 'o-identification',
        'phone' => 'o-phone',
        'address' => 'o-map-pin',
        'calendar' => 'o-calendar',
        'contract' => 'o-document-text',
        'warning' => 'o-exclamation-triangle',
        'terminate' => 'o-x-circle',
        'money' => 'o-banknotes',
        'link-account' => 'o-link',
        'attendance' => 'o-clock',
        'check-in' => 'o-arrow-right-on-rectangle',
        'check-out' => 'o-arrow-left-on-rectangle',
        'calculate' => 'o-calculator',
        'leave' => 'o-calendar-days',
        'approve' => 'o-check-circle',
        'reject' => 'o-x-circle',
        'payroll' => 'o-banknotes',
        'payslip' => 'o-document-text',
        'finalize' => 'o-lock-closed',
        'print' => 'o-printer',
        'review' => 'o-exclamation-circle',
        'now' => 'o-bolt',
        'balance' => 'o-scale',
        'hourly' => 'o-clock',
        'note' => 'o-chat-bubble-bottom-center-text',
        'reopen' => 'o-lock-open',
        'process' => 'o-arrow-path',
        'party' => 'o-identification',
        'economic-code' => 'o-hashtag',
        'currency' => 'o-currency-dollar',
        'exchange-rate' => 'o-arrows-right-left',
        'contact' => 'o-user-circle',
        'profile' => 'o-identification',
        'site' => 'o-building-storefront',
        'purchase' => 'o-shopping-bag',
        'call' => 'o-phone',
        'telegram' => 'o-paper-airplane',
        'site-form' => 'o-clipboard-document-list',
        'timeline' => 'o-queue-list',
        'lead' => 'o-funnel',
        'assign' => 'o-user-plus',
        'segment' => 'o-chart-pie',
        'recalculate' => 'o-arrow-path',
        'category' => 'o-tag',
        'sku' => 'o-qr-code',
        'unit' => 'o-scale',
        'woocommerce' => 'o-link',
        'warehouse' => 'o-building-storefront',
        'stock-in' => 'o-arrow-down-tray',
        'stock-out' => 'o-arrow-up-tray',
        'stock-adjust' => 'o-adjustments-horizontal',
        'stock-transfer' => 'o-arrows-right-left',
        'message' => 'o-chat-bubble-left-right',
        'send' => 'o-paper-airplane',
        'archive' => 'o-archive-box',
        'inbox' => 'o-inbox',
        'ticket' => 'o-lifebuoy',
        'history' => 'o-clock',
        'blog' => 'o-newspaper',
        'blog-tag' => 'o-bookmark',
        'image' => 'o-photo',
        'reading-time' => 'o-clock',
        'back' => 'o-arrow-right',
        'next' => 'o-arrow-left',
        'preview' => 'o-eye',
        'site-builder' => 'o-window',
        'page' => 'o-document',
        'template' => 'o-rectangle-group',
        'header' => 'o-view-columns',
        'footer' => 'o-bars-3-bottom-left',
        'drag-handle' => 'o-arrows-up-down',
        'outline' => 'o-list-bullet',
        'locked' => 'o-lock-closed',
        'oversight' => 'o-clipboard-document-check',
        'reminder' => 'o-bell-alert',
        'undo' => 'o-arrow-uturn-left',
        'info' => 'o-information-circle',
        'file' => 'o-paper-clip',
        'download' => 'o-arrow-down-tray',
        'flowchart' => 'o-share',
        'version' => 'o-code-bracket-square',
        'cancel' => 'o-x-circle',
        'campaign' => 'o-megaphone',
        'trigger' => 'o-bolt',
        'simulation' => 'o-beaker',
        'tracking' => 'o-qr-code',
        'pack' => 'o-archive-box',
    ],

];
